[variables]
GIT_LFS_SKIP_SMUDGE = "1"

[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase - Flask app ready"']

[start]
cmd = 'python web_interface.py'
