services:
  - type: web
    name: dylan-content-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_interface.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: LINKEDIN_ACCESS_TOKEN
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
